function [HCE,SCE,Means,ToMap]=Summary2NZ(Case,returnperiods,RedEvent,TrueEvent,TrueRGM) 

% This function is used to compute the summary results for a set of 
% ground motion maps (for earthquake scenarios, use Summary1NZ.m). The
% summary is based on a comparison to the "true" hazard. 
% HCE is the hazard curve errors for every site and return period. 
% SCE is the set of spatial correlation errors (if Case='MCS')
% Means is a 1 by 2 vector [MHCE MSCE]  
% ToMap is a table with information to map the reduced and "true return period ground motion
% maps 

% Case identifies whether TrueRGM was provided or computed from a conventional MCS run.
% Case='Given'. True hazard given. Input only: RedEvent, TrueRGM. Let TrueEvent=999.
% Case='MCS'. True hazard from MCS. Input only: RedEvent, TrueEvent. Let TrueRGM=999.

% returnperiods is vector of returnperiods at which hazard curves are
%   matched, e.g. (250 500 1000 2500)

% RedEvent is the Event structure for the set of earthquake scenarios being
% summarized. It is generated by running SeisEvent1NZ.m with number of
% maps=num of eq scenarios. It is used to provide the mean and sigma of the
% ground motion.

% TrueEvent is the "true" set of ground motion maps if the "true" hazard is
% provided by a MCS analysis.

% TrueRGM is the "true" hazard curve information 

% Compute TrueRGM and RedRGM for whichever Case is being run
if strcmp(Case,'MCS')==1
    [~,TrueRGM]=HazAnaResult2NZ(TrueEvent,returnperiods,TrueRGM);   % Case 'MCS'
end
[~,RedRGM]=HazAnaResult2NZ(RedEvent,returnperiods,TrueRGM);     

% Compute hazard curve errors (HCE) as in Han and Davidson (2012, Eq. 13)
% and make a table to use to import into GIS to map, for every return period, (1) ground motions 
% from reduced set, (2) "true" ground motions, or (3) error between the two

sizeTrueRGM=size(TrueRGM);
sitenum=sizeTrueRGM(1);         % Number of sites
rpnum=length(returnperiods);    % Number of return periods
HCE=zeros(sitenum,rpnum);
SCE=zeros(sitenum,sitenum);
Means=zeros(1,2);
ToMap=zeros(sitenum,(rpnum*3));

for i=1:sitenum
    for j=1:rpnum
        HCE(i,j)=(TrueRGM(i,j)-RedRGM(i,j))/TrueRGM(i,j);
        
        ToMap(i,((3*j)-2))=RedRGM(i,j);
        ToMap(i,((3*j)-1))=TrueRGM(i,j);
        ToMap(i,(3*j))=TrueRGM(i,j)-RedRGM(i,j);
    end
end

% Compute summary measure mean hazard curve error (MHCE) as in Han and Davidson (2012, Eq. 14)
Means(1,1)=(sum(sum(abs(HCE)))/(sitenum*rpnum));

% Draw histogram of HCEs using 20 bins (Comment out if running on cluster)
m1=sitenum*rpnum;
figure;
hist(reshape(HCE,1,m1),20);
title('Histogram of hazard curve errors');
xlabel('Hazard curve errors');
ylabel('Frequency');

if strcmp(Case,'MCS')==1   % Case 'MCS' is the only one where spatial correlation can be computed

    % Compute spatial correlation errors (SCE) as in Han and Davidson (2012, Eq. 15)
    Redcc=spatialcorre(RedEvent);
    Truecc=spatialcorre(TrueEvent);

    for a=1:sitenum
        for b=1:sitenum
            SCE(a,b)=Truecc(a,b)-Redcc(a,b);
            SCE(a,b)=double(SCE(a,b));
        end
    end

    % Compute summary measure mean spatial correlation error (MSCE) as in Han and Davidson (2012, Eq. 16)
    Means(1,2)=(sum(sum(abs(SCE))))/((sitenum*(sitenum-1))/2);

    % Draw histogram of SCEs using 20 bins (Comment out if running on cluster)
    m2=sitenum*sitenum;
    figure;
    SCEnozeros=SCE(SCE~=0);         % Consider only nonzero values (not those on diag or lower triangle)
    hist(SCEnozeros,20);
    title('Histogram of spatial correlation errors');
    xlabel('Spatial correlation errors');
    ylabel('Frequency');

end




