function [HCE,Means,ToMap]=Summary1NZ(Case,returnperiods,RedEvent,TrueEvent,TrueRGM) 

% This function is used to compute the summary results for a set of 
% earthquake scenarios (for ground motion maps, use Summary2NZ.m). The
% summary is based on a comparison to the "true" hazard. 
% HCE is the hazard curve errors for every site and return period. 
% Means is a 1 by 2 vector [MHCE MSCE] (MSCE is left blank here; it's only used in Summary2NZ.m). 
% ToMap is a table with information to map the reduced and "true return period ground motion
% maps 

% Case identifies whether TrueRGM was provided or computed from a conventional MCS run.
% Case='Given'. True hazard given. Input only: RedEvent, TrueRGM. Let TrueEvent=999.
% Case='MCS'. True hazard from MCS. Input only: RedEvent, TrueEvent. Let TrueRGM=999.

% returnperiods is vector of returnperiods at which hazard curves are
%   matched, e.g. (250 500 1000 2500)

% RedEvent is the Event structure for the set of earthquake scenarios being
% summarized. It is generated by running SeisEvent1NZ.m with number of
% maps=num of eq scenarios. It is used to provide the mean and sigma of the
% ground motion.

% TrueEvent is the "true" set of ground motion maps if the "true" hazard is
% provided by a MCS analysis.

% TrueRGM is the "true" hazard curve information 

% Compute TrueRGM and RedRGM for whichever Case is being run
if strcmp(Case,'MCS')==1
    [~,TrueRGM]=HazAnaResult2NZ(TrueEvent,returnperiods,TrueRGM);   
end
[~,RedRGM]=HazAnaResult1NZ(RedEvent,returnperiods,TrueRGM);   

% Compute hazard curve errors (HCE) as in Han and Davidson (2012, Eq. 13)
% and make a table to use to import into GIS to map, for every return period, (1) ground motions 
% from reduced set, (2) "true" ground motions, or (3) error between the two

sizeTrueRGM=size(TrueRGM);
sitenum=sizeTrueRGM(1);         % Number of sites
rpnum=length(returnperiods);    % Number of return periods
HCE=zeros(sitenum,rpnum);
Means=zeros(1,2);
ToMap=zeros(sitenum,(rpnum*3));

for i=1:sitenum
    for j=1:rpnum
        HCE(i,j)=(TrueRGM(i,j)-RedRGM(i,j))/TrueRGM(i,j);   
        
        ToMap(i,((3*j)-2))=RedRGM(i,j);
        ToMap(i,((3*j)-1))=TrueRGM(i,j);
        ToMap(i,(3*j))=TrueRGM(i,j)-RedRGM(i,j);
    end
end

% Compute summary measure mean hazard curve error (MHCE) as in Han and Davidson (2012, Eq. 14)
Means(1,1)=(sum(sum(abs(HCE)))/(sitenum*rpnum));

% Draw histogram of HCEs using 20 bins (Comment out if running on cluster)
m1=sitenum*rpnum;
figure;
hist(reshape(HCE,1,m1),20);
title('Histogram of hazard curve errors');
xlabel('Hazard curve errors');
ylabel('Frequency');





